baseURL = 'http://girolamodaschio.it/'
copyright = "{year}"
languageCode = 'en-us'
theme = 'lowkey'
title = 'Girolamo da Schio'
enableRobotsTXT = true

# List Config
summaryLength= 15
paginate = 5

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false
